package ai

import (
	"context"
	"fmt"

	"github.com/razorpay-hack/ai-finance-controller/internal/models"
)

// OfflineClient provides grounded, deterministic financial diagnoses when offline or API key is absent.
type OfflineClient struct{}

// NewOfflineClient creates an offline fallback investigation client.
func NewOfflineClient() *OfflineClient {
	return &OfflineClient{}
}

// InvestigateException generates an evidence-grounded diagnosis and suggested action deterministically.
func (c *OfflineClient) InvestigateException(_ context.Context, req InvestigationRequest) (*InvestigationResponse, error) {
	var diagnosis string
	var action string
	confidence := "HIGH"

	switch req.Category {
	case models.CategoryDuplicateSettlement:
		diagnosis = fmt.Sprintf("Multiple settlement entries were generated by the payment gateway for record %s, indicating either duplicate gateway polling or an un-deduplicated webhook re-delivery.", req.RecordID)
		action = "Inspect gateway webhook transmission logs and verify unique payment transaction IDs before releasing settlement hold."

	case models.CategoryAmountMismatch:
		diagnosis = fmt.Sprintf("Settled amount diverges from internal ledger gross amount beyond the 2.5%% fee ceiling for %s. This often points to unannounced MDR rate updates or un-notified chargeback deductions.", req.RecordID)
		action = "Reconcile applied merchant fee rate against the gateway service level agreement (SLA) contract schedule."

	case models.CategorySettledNotBanked:
		diagnosis = fmt.Sprintf("Settlement batch was acknowledged by gateway settlement system but failed to materialize as a credit on the nodal bank statement for %s.", req.RecordID)
		action = "Contact acquiring bank treasury desk with the nodal batch reference to trace delayed clearing or NEFT/RTGS settlement reject."

	case models.CategoryPartialCredit:
		diagnosis = fmt.Sprintf("Bank credited an amount lower than the expected settlement batch aggregate for %s. Discrepancy indicates bank withholding for rolling reserve or tax deduction at source (TDS).", req.RecordID)
		action = "Verify bank nodal statement deduction breakdown and confirm whether a rolling reserve or GST hold was applied."

	case models.CategoryBankAmountMismatch:
		diagnosis = fmt.Sprintf("Bank credit exceeds the expected settlement batch total for %s without an associated credit adjustment note.", req.RecordID)
		action = "Request credit advice memo from nodal operations to confirm if this includes multi-batch consolidation or prior cycle reversals."

	case models.CategoryBankedNotSettled:
		diagnosis = fmt.Sprintf("Unexplained bank deposit credited to nodal account with no corresponding settlement batch record (%s).", req.RecordID)
		action = "Request bank credit advice and remitters details from acquiring bank to map unidentified credit."

	default:
		diagnosis = fmt.Sprintf("Financial discrepancy detected for %s: %s", req.RecordID, req.Reason)
		action = "Review source record timestamps, merchant status, and audit evidence."
		confidence = "MEDIUM"
	}

	return &InvestigationResponse{
		Diagnosis:       diagnosis,
		SuggestedAction: action,
		Confidence:      confidence,
		Model:           "offline-deterministic-synthesizer",
		PromptVersion:   PromptVersion,
		LatencyMs:       1,
	}, nil
}
